# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 86bc61fb827e4bb1d502439fcb1742df13dfd06ff3242ae20f7c7a8a1e90b263835221fa46306ef2ce16af6c734347302807dfee3ee547fb9eba6e8bf9c304dc

test:
  secret_key_base: 1d16fdc8ac95a3acfdc8117f502aec3b8e7fcbabd97430869c26db04002e4389ead8aa47bfff16659e43e4ce6007511ce9fbab94cb311aa2e890244e9cd88af1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
